/**
 * Agent model-resolution preflight (issue #2271 bug 4; issue #2680).
 *
 * Agent model strings (DEFAULT_MODELS plus user `agents.<role>.model` /
 * `swarms.<id>.agents.<role>.model` overrides) are handed to the OpenCode host
 * unvalidated. When one does not resolve ("Model not found", "Forbidden"),
 * dispatch-lanes classifies the failure as permanent, the affected agent never
 * runs, and the plan-critic gate wedges into manual `approve_plan_critic`
 * overrides because no APPROVED verdict is ever produced.
 *
 * This module validates the FINAL effective model selection for every ENABLED
 * legacy and prefixed multi-swarm role (issue #2680) against the live provider
 * catalog (`client.provider.list()`), reusing the exact-name resolution
 * helpers from src/config/agent-model.ts. Every check is FAIL-OPEN: if the
 * catalog is unreachable or malformed, results come back `unknown` and callers
 * must proceed — the preflight only acts on a POSITIVE confirmation that a
 * model does not resolve (or that no final selection exists at all, the
 * catalog-independent `missing-selection` class).
 */

import type { OpencodeClient } from '@opencode-ai/sdk';
import { resolvePrimaryAgentNames } from '../agents/index';
import {
	resolveConfiguredAgentModel,
	resolveEffectiveAgentOverride,
	resolveRegisteredAgentModel,
} from '../config/agent-model';
import { ALL_AGENT_NAMES, DEFAULT_MODELS } from '../config/constants';
import { stripKnownSwarmPrefix } from '../config/schema';
import type { PluginConfig } from '../config/schema.js';

/** Tight bound for the catalog HTTP call — it runs on init/doctor paths. */
export const PROVIDER_LIST_TIMEOUT_MS = 2_000;

export interface ConfiguredAgentModel {
	/** Agent role the model is configured for. */
	agent: string;
	/** Full model id in `provider/model` form. Empty when no final selection exists. */
	model: string;
	/** Where the value came from. */
	source: 'default' | 'override' | 'fallback';
	/**
	 * Issue #2680: whether the entry's role is registered as a primary agent
	 * (OpenCode's UI owns its model selection) or a dispatchable subagent.
	 */
	mode?: 'primary' | 'subagent';
}

export type ModelResolutionStatus =
	| 'ok'
	| 'unresolved'
	| 'unknown'
	| 'missing-selection'
	| 'host-controlled';

export interface ModelResolution {
	agent: string;
	model: string;
	source: ConfiguredAgentModel['source'];
	status: ModelResolutionStatus;
	/** Human-readable explanation for non-ok statuses. */
	detail?: string;
	mode?: ConfiguredAgentModel['mode'];
}

export interface ModelPreflightResult {
	/** False when the catalog could not be fetched — every entry is `unknown`. */
	catalogAvailable: boolean;
	resolutions: ModelResolution[];
}

/**
 * Split a model id into its provider and model parts. Returns null for ids
 * without a provider prefix (e.g. a bare model name) — those cannot be
 * validated against a provider catalog.
 */
export function splitModelId(
	model: string,
): { provider: string; model: string } | null {
	const separator = model.indexOf('/');
	if (separator <= 0 || separator === model.length - 1) return null;
	return {
		provider: model.slice(0, separator),
		model: model.slice(separator + 1),
	};
}

/**
 * Collect every model id the swarm could dispatch with: DEFAULT_MODELS
 * entries, user agent overrides, and declared fallback_models. Overriding one
 * role replaces its default (mirrors getModelForAgent precedence).
 *
 * Superseded by collectEnabledAgentModels (issue #2680): this legacy view
 * enumerates the top-level config plus a blanket DEFAULT_MODELS pass and
 * cannot see multi-swarm per-swarm selections or enabled-role gating. Retained
 * unchanged for API compatibility; runModelPreflight no longer consumes it.
 */
export function collectConfiguredAgentModels(
	config?: PluginConfig,
): ConfiguredAgentModel[] {
	const collected: ConfiguredAgentModel[] = [];
	const overriddenAgents = new Set<string>();
	const overrides = config?.agents ?? {};
	for (const [agent, override] of Object.entries(overrides)) {
		if (typeof override?.model === 'string' && override.model.trim()) {
			collected.push({
				agent,
				model: override.model.trim(),
				source: 'override',
			});
			overriddenAgents.add(agent);
		}
		for (const fallback of override?.fallback_models ?? []) {
			if (typeof fallback === 'string' && fallback.trim()) {
				collected.push({
					agent,
					model: fallback.trim(),
					source: 'fallback',
				});
			}
		}
	}
	for (const [agent, model] of Object.entries(DEFAULT_MODELS)) {
		if (overriddenAgents.has(agent)) continue;
		collected.push({ agent, model, source: 'default' });
	}
	return collected;
}

/**
 * Issue #2680: optional roles whose registration is feature-gated. Every other
 * role in ALL_AGENT_NAMES is generated by createSwarmAgents unless its merged
 * `agents.<role>.disabled` entry is true. Kept in lockstep with the explicit
 * blocks in createSwarmAgents (src/agents/index.ts) — the parity test in
 * tests/unit/services/model-preflight-2680.test.ts guards the mapping.
 */
const FEATURE_GATED_ROLES: ReadonlyMap<
	string,
	(config?: PluginConfig) => boolean
> = new Map([
	['council_generalist', (c) => c?.council?.general?.enabled === true],
	['council_skeptic', (c) => c?.council?.general?.enabled === true],
	['council_domain_expert', (c) => c?.council?.general?.enabled === true],
	['docs_design', (c) => c?.design_docs?.enabled === true],
	['designer', (c) => c?.ui_review?.enabled === true],
]);

const ALWAYS_ON_ROLES: readonly string[] = ALL_AGENT_NAMES.filter(
	(role) => !FEATURE_GATED_ROLES.has(role),
);

/**
 * Issue #2680: compute the generated agent names the plugin would register for
 * this configuration — the "enabled role" domain the preflight must validate.
 * Mirrors createAgents' generation rules (legacy single default swarm vs
 * per-swarm prefixing; object-level top-level merge; disabled exclusion;
 * feature-gated roles only while their flag is on). The live
 * swarmState.generatedAgentNames registry stays authoritative when available;
 * this computation is the config-only fallback (doctor, unit tests) and is
 * drift-guarded by the parity test.
 */
export function enumerateEnabledAgentRoles(config?: PluginConfig): string[] {
	const names: string[] = [];
	const emitSwarm = (swarmId: string, isDefault: boolean) => {
		const prefix = isDefault ? '' : `${swarmId}_`;
		// Object-level merge identical to createAgents (src/agents/index.ts):
		// a swarm-specific entry replaces a top-level entry for the same role.
		const swarmAgents = config?.swarms?.[swarmId]?.agents;
		const merged: Record<string, { disabled?: boolean } | undefined> =
			config?.agents
				? { ...config.agents, ...(swarmAgents ?? {}) }
				: (swarmAgents ?? {});
		for (const role of ALWAYS_ON_ROLES) {
			if (merged?.[role]?.disabled === true) continue;
			names.push(`${prefix}${role}`);
		}
		for (const [role, flagEnabled] of FEATURE_GATED_ROLES) {
			if (!flagEnabled(config)) continue;
			if (merged?.[role]?.disabled === true) continue;
			names.push(`${prefix}${role}`);
		}
	};
	const swarms = config?.swarms;
	if (swarms && Object.keys(swarms).length > 0) {
		for (const swarmId of Object.keys(swarms)) {
			emitSwarm(swarmId, swarmId === 'default');
		}
	} else {
		emitSwarm('default', true);
	}
	return names;
}

/** Options for the enabled-role preflight (issue #2680). */
export interface EnabledAgentPreflightOptions {
	/**
	 * The live registry of generated agent names the host actually registered
	 * (swarmState.generatedAgentNames). Authoritative when provided; the
	 * config-only enumeration is the fallback.
	 */
	generatedAgentNames?: readonly string[];
	/**
	 * The registered agents map (name → { model, mode }) as produced by
	 * createAgents/getAgentConfigs. When provided, `mode` comes from it;
	 * otherwise primaries are derived via resolvePrimaryAgentNames.
	 */
	registeredAgents?: Record<string, { model?: unknown; mode?: unknown }>;
}

/**
 * Issue #2680: collect the FINAL effective model selection for every enabled
 * legacy and prefixed multi-swarm role, plus each role's explicitly configured
 * fallback entries. Final selections are computed with the shipped exact-name
 * helpers (resolveRegisteredAgentModel / resolveConfiguredAgentModel) so
 * defaults, swarm prefixes, and the object-level merge match dispatch reality.
 *
 * Outcome classes (see resolveAgainstCatalog):
 * - an explicitly configured but blank model, or a registry name that resolves
 *   to no target at all, yields an EMPTY model — the distinct
 *   `missing-selection` class (never silently treated as a successful default);
 * - primary roles are tagged `mode: 'primary'` → `host-controlled` (OpenCode's
 *   UI owns their selection);
 * - fallback entries appear only when explicitly configured and recorded —
 *   never synthesized (curator roles inherit explorer's chain at runtime via
 *   resolveFallbackModel; that inheritance is documented, not duplicated here).
 */
export function collectEnabledAgentModels(
	config?: PluginConfig,
	opts?: EnabledAgentPreflightOptions,
): ConfiguredAgentModel[] {
	const names =
		opts?.generatedAgentNames && opts.generatedAgentNames.length > 0
			? [...opts.generatedAgentNames]
			: enumerateEnabledAgentRoles(config);
	const primaryNames: Set<string> = opts?.registeredAgents
		? new Set(
				Object.entries(opts.registeredAgents)
					.filter(([, value]) => value?.mode === 'primary')
					.map(([name]) => name),
			)
		: resolvePrimaryAgentNames(names, config?.default_agent).primaryNames;
	const collected: ConfiguredAgentModel[] = [];
	for (const name of names) {
		const mode: ConfiguredAgentModel['mode'] = primaryNames.has(name)
			? 'primary'
			: 'subagent';
		// The exact-name helpers require a defined config; with no config at
		// all there is no override and no target resolution — defaults still
		// apply through the registry names below.
		const effective = config
			? resolveEffectiveAgentOverride(config, name)
			: undefined;
		const configuredModel = config
			? resolveConfiguredAgentModel(config, name)
			: undefined;
		const finalModel = config
			? resolveRegisteredAgentModel(config, name)
			: (DEFAULT_MODELS[stripKnownSwarmPrefix(name)] ?? DEFAULT_MODELS.default);
		if (
			effective &&
			typeof effective.model === 'string' &&
			effective.model.trim() === ''
		) {
			// Explicitly configured but blank: the precedence chain would
			// silently fall through to a default — record the missing
			// selection instead so it cannot pass preflight unnoticed.
			collected.push({ agent: name, model: '', source: 'override', mode });
		} else {
			collected.push({
				agent: name,
				model: finalModel ?? '',
				source: configuredModel !== undefined ? 'override' : 'default',
				mode,
			});
		}
		for (const fallback of effective?.fallbackModels ?? []) {
			if (typeof fallback === 'string' && fallback.trim()) {
				collected.push({
					agent: name,
					model: fallback.trim(),
					source: 'fallback',
					mode,
				});
			}
		}
	}
	return collected;
}

/** Provider catalog snapshot: provider id → set of model ids. */
export type ProviderCatalog = Map<string, Set<string>>;

/**
 * Issue #2271 review finding PRR-006: the delegation-gate critic preflight
 * calls this on every critic dispatch — a short TTL cache keeps the per-dispatch
 * cost off the host while staying fresh enough for interactive model-config
 * fixes. Keyed per-client (WeakMap) so a swapped OpenCode client never sees
 * another client's catalog; gate call sites additionally invalidate the cache
 * after a positive unresolved verdict so a fixed config takes effect on the
 * very next attempt instead of after the TTL.
 */
const CATALOG_CACHE_TTL_MS = 30_000;
let catalogCacheByClient = new WeakMap<
	OpencodeClient,
	{ fetchedAt: number; catalog: ProviderCatalog }
>();
/**
 * PR #2782 review PRR-005: bumped by invalidateProviderCatalogCache so an
 * in-flight fetch that started BEFORE an invalidation cannot write its
 * (pre-invalidation) catalog into the NEW WeakMap after it lands.
 */
let catalogCacheEpoch = 0;

/** Test/gate seam: drop the cached catalogs (used after config changes and denials). */
export function invalidateProviderCatalogCache(): void {
	catalogCacheEpoch++;
	catalogCacheByClient = new WeakMap();
}

/**
 * PR #2782 review PRR-001: neutralize control characters before interpolating
 * config- or host-sourced strings (model ids, agent names, provider detail)
 * into console.warn / thrown-Error text. Newlines forge multi-line
 * plugin-looking output and ESC sequences drive the terminal; control runs
 * collapse to a single space (same policy as the doctor's stripControlChars).
 */
export function sanitizePreflightText(value: string): string {
	// biome-ignore lint/suspicious/noControlCharactersInRegex: intentionally matching control chars to strip them
	return value.replace(/[\x00-\x1f\x7f]+/g, ' ');
}

/**
 * Fetch the provider catalog. Returns null when the catalog cannot be
 * obtained or parsed — callers fail open on null.
 */
export async function fetchProviderCatalog(
	client: OpencodeClient | null,
): Promise<ProviderCatalog | null> {
	if (!client) return null;
	const cached = catalogCacheByClient.get(client);
	if (cached && Date.now() - cached.fetchedAt < CATALOG_CACHE_TTL_MS) {
		return cached.catalog;
	}
	const epochAtFetchStart = catalogCacheEpoch;
	let response: Awaited<ReturnType<OpencodeClient['provider']['list']>>;
	try {
		response = await _internals.providerList(client);
	} catch {
		return null;
	}
	const all = response?.data?.all;
	if (!Array.isArray(all)) return null;
	const catalog: ProviderCatalog = new Map();
	for (const provider of all) {
		if (typeof provider?.id !== 'string') continue;
		const models = new Set<string>();
		// PRR-002: an array-shaped `models` would pass typeof === 'object' and
		// index its numeric keys into the Set, making every real lookup miss.
		// The pinned SDK types models as a record; refuse arrays defensively.
		if (
			provider.models &&
			typeof provider.models === 'object' &&
			!Array.isArray(provider.models)
		) {
			for (const modelKey of Object.keys(provider.models)) {
				models.add(modelKey);
			}
		}
		catalog.set(provider.id, models);
	}
	// PRR-005: a fetch that raced an invalidation is not cached — its data
	// predates the invalidation, and the next call refetches fresh.
	if (epochAtFetchStart === catalogCacheEpoch) {
		catalogCacheByClient.set(client, { fetchedAt: Date.now(), catalog });
	}
	return catalog;
}

/**
 * Validate collected models against a catalog. Classification order (issue
 * #2680): an EMPTY model is the catalog-independent `missing-selection` class;
 * a primary role is `host-controlled` (OpenCode's UI owns its selection —
 * never a preflight failure and never a consumer-default warning); otherwise
 * the catalog decides — a model whose provider is absent from the catalog, or
 * whose provider exists but does not list the model, is `unresolved` — but
 * only when the catalog itself was successfully fetched (callers must treat a
 * null catalog as fail-open, never unresolved).
 */
export function resolveAgainstCatalog(
	models: ConfiguredAgentModel[],
	catalog: ProviderCatalog | null,
): ModelPreflightResult {
	const classifySelection = (entry: ConfiguredAgentModel): ModelResolution => {
		if (entry.model.trim() === '') {
			return {
				...entry,
				status: 'missing-selection' as const,
				detail:
					'enabled role has no final model selection: the exact agent target resolved to no configured model and no default (blank model override or a stale swarm registry entry). Fix agents.<role>.model in opencode-swarm.json — the matching swarm override wins over the top-level entry.',
			};
		}
		if (entry.mode === 'primary') {
			return {
				...entry,
				status: 'host-controlled' as const,
				detail:
					'primary agent: OpenCode UI owns the model selection; the registered model is intentionally not applied',
			};
		}
		const split = splitModelId(entry.model);
		if (!split) {
			return {
				...entry,
				status: 'unknown' as const,
				detail:
					'model id has no provider prefix; resolution not checked against the catalog',
			};
		}
		const providerModels = catalog?.get(split.provider);
		if (providerModels === undefined) {
			return {
				...entry,
				status: 'unresolved' as const,
				detail: `provider "${split.provider}" is not present in the provider catalog`,
			};
		}
		if (!providerModels.has(split.model)) {
			return {
				...entry,
				status: 'unresolved' as const,
				detail: `provider "${split.provider}" does not list model "${split.model}"`,
			};
		}
		return { ...entry, status: 'ok' as const };
	};
	if (catalog === null) {
		return {
			catalogAvailable: false,
			resolutions: models.map((entry) =>
				entry.model.trim() === ''
					? classifySelection(entry)
					: {
							...entry,
							status: 'unknown' as const,
							detail:
								'provider catalog unavailable; model resolution not checked',
						},
			),
		};
	}
	return {
		catalogAvailable: true,
		resolutions: models.map(classifySelection),
	};
}

/**
 * Issue #2680: render the operator warning for a preflight result. Reports
 * ONLY actionable classes (`unresolved`, `missing-selection`) — ok/unknown
 * entries and host-controlled primaries stay silent, so disabled, optional,
 * and merely-uninvoked roles never produce consumer-default noise. Returns
 * null when there is nothing to report.
 */
export function formatModelPreflightWarning(
	result: ModelPreflightResult,
): string | null {
	const reportable = result.resolutions.filter(
		(resolution) =>
			resolution.status === 'unresolved' ||
			resolution.status === 'missing-selection',
	);
	if (reportable.length === 0) return null;
	const lines = reportable.map((resolution) => {
		// PRR-001: agent/model/detail are config-sourced; control characters
		// (newlines, ESC) must not structure the surrounding warning text.
		const label =
			resolution.source === 'fallback'
				? `${sanitizePreflightText(resolution.agent)} (fallback entry)`
				: sanitizePreflightText(resolution.agent);
		if (resolution.status === 'missing-selection') {
			return `  ${label}: no final model selection — ${sanitizePreflightText(resolution.detail ?? '')}`;
		}
		return `  ${label}: ${sanitizePreflightText(resolution.model)} (${sanitizePreflightText(resolution.detail ?? 'does not resolve')})`;
	});
	return (
		`[opencode-swarm] WARNING: ${reportable.length} enabled agent model selection(s) failed preflight:\n` +
		`${lines.join('\n')}\n` +
		'Dispatching these roles will fail permanently ("Model not found"/"Forbidden"). ' +
		'Fix the effective model configuration in opencode-swarm.json — the matching swarm override wins over top-level agents.<role>.model. ' +
		'fallback_models entries only serve transient runtime failures; configure a resolvable primary model for the affected role.'
	);
}

/**
 * End-to-end preflight: collect the FINAL effective selection for every
 * enabled role (issue #2680), fetch the catalog, and resolve. Fail-open on
 * every catalog error.
 */
export async function runModelPreflight(
	config: PluginConfig | undefined,
	client: OpencodeClient | null,
	opts?: EnabledAgentPreflightOptions,
): Promise<ModelPreflightResult> {
	const models = collectEnabledAgentModels(config, opts);
	const catalog = await fetchProviderCatalog(client);
	return resolveAgainstCatalog(models, catalog);
}

/**
 * Resolves a single model id against the live catalog for gate preflights.
 * Returns 'unknown' whenever the catalog cannot be fetched — gates must only
 * block on 'unresolved'.
 */
export async function checkSingleModelResolution(
	model: string,
	client: OpencodeClient | null,
): Promise<ModelResolutionStatus> {
	const catalog = await fetchProviderCatalog(client);
	if (catalog === null) return 'unknown';
	const split = splitModelId(model);
	if (!split) return 'unknown';
	const providerModels = catalog.get(split.provider);
	if (providerModels === undefined || !providerModels.has(split.model)) {
		return 'unresolved';
	}
	return 'ok';
}

/**
 * Verified keyless opencode zen roster (issue #3022, captured 2026-10-02 on a
 * clean @opencode/cli 2.0.21 container via `opencode run -m opencode/<id>`).
 * Cross-pinned against tests/fixtures/opencode-zen-keyless-roster.json by
 * tests/unit/config/default-models-roster-guard.test.ts. REFRESH PROCEDURE:
 * re-run the per-id probe matrix (failures print `Model unavailable: <id>`
 * while exiting 0 — match text, not exit codes), update BOTH this list and the
 * fixture, then rotate src/config/constants.ts; the guard test failing after a
 * refresh is the mechanism working.
 */
export const VERIFIED_KEYLESS_MODEL_ROSTER: readonly string[] = [
	'opencode/big-pickle',
	'opencode/longcat-2.5-preview-free',
	'opencode/nemotron-3-ultra-free',
	'opencode/space-bunny-free',
	'opencode/mimo-v2.6-flash-free',
	'opencode/fledge-alpha-free',
	'opencode/nemotron-3.5-lightning-free',
	'opencode/muse-spark-1.3-contributor-free',
];

/**
 * Issue #3022 (AC4): pure, clientless roster check. Given the configured agent
 * models (a `string[]` of model ids or a DEFAULT_AGENT_CONFIGS-shaped record of
 * `{model, fallback_models}` entries) and a roster of known-good ids, returns
 * one bounded warning per configured id that is NOT in the roster (deduped),
 * and NO warnings when every id resolves. No I/O, no network — safe to run on
 * hosts without an OpencodeClient (OpenCode v2 startup) where the
 * catalog-backed {@link runModelPreflight} degrades to all-`unknown`.
 */
export function collectModelRosterWarnings(
	models:
		| readonly string[]
		| Record<string, { model?: string; fallback_models?: string[] }>,
	roster: readonly string[],
): string[] {
	const known = new Set(roster);
	const toCheck: string[] = [];
	if (Array.isArray(models)) {
		toCheck.push(...models);
	} else if (models && typeof models === 'object') {
		for (const entry of Object.values(models)) {
			if (!entry || typeof entry !== 'object') continue;
			if (typeof entry.model === 'string' && entry.model.length > 0) {
				toCheck.push(entry.model);
			}
			for (const fb of entry.fallback_models ?? []) {
				if (typeof fb === 'string' && fb.length > 0) toCheck.push(fb);
			}
		}
	}
	const seen = new Set<string>();
	const warnings: string[] = [];
	for (const model of toCheck) {
		if (seen.has(model)) continue;
		seen.add(model);
		// The verified roster covers ONLY the opencode zen provider (#3022
		// review round 1): other providers (anthropic/openai/xai/...) resolve
		// through their own catalogs and are out of scope — warning about them
		// would claim a hard failure that never happens.
		if (!model.startsWith('opencode/')) continue;
		if (!known.has(model)) {
			warnings.push(
				`[opencode-swarm] model preflight: ${model} is not in the verified opencode zen keyless roster (tests/fixtures/opencode-zen-keyless-roster.json); if this is a zen free-tier id, delegation will fail with "Model unavailable" until the roster/constants are refreshed.`,
			);
		}
	}
	return warnings;
}

export const _internals = {
	/** Injectable seam for the SDK catalog call (tests substitute this). */
	providerList: async (client: OpencodeClient) => {
		let timer: ReturnType<typeof setTimeout> | undefined;
		try {
			return await Promise.race([
				client.provider.list(),
				new Promise<never>((_, reject) => {
					timer = setTimeout(
						() => reject(new Error('provider list timed out')),
						PROVIDER_LIST_TIMEOUT_MS,
					);
				}),
			]);
		} finally {
			if (timer) clearTimeout(timer);
		}
	},
};
